import type { Metadata } from "next";
import { Inter, Comfortaa, Roboto } from 'next/font/google'
import "./globals.css";
import ClientLayout from './client-layout';

const inter = Inter({ subsets: ['latin'] })
const comfortaa = Comfortaa({ subsets: ['latin'], weight: ['400'] })
const roboto = Roboto({ subsets: ['latin'], weight: ['400', '900'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="emotion-insertion-point" content="" />
      </head>
      <body className={`${inter.className} ${comfortaa.className} ${roboto.className}`}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  )
}
